name=TFT35_V1_F407
version=1.0.0
author=Mylonas Dimitris
maintainer=Mylonas Dimitris milonasdimitris9@gmail.com
sentence=High-performance FSMC/DMA driver and Grid-based UI framework for STM32F407 TFT35 modules.
paragraph=Library for STM32F407VET6 TFT modules using FSMC with DMA support and a grid-based UI system.
category=Display
url=https://github.com/MylonasDimitris/TFT35_V1_F407
architectures=stm32
depends=SdFat
